name: Python Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
      - name: Create virtual environment and install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e .
          uv pip install pyright ruff
      
      - name: Run Pyright type checker
        run: |
          source .venv/bin/activate
          echo "::group::Pyright Type Checking"
          pyright src/dv
          echo "::endgroup::"
      
      - name: Run Ruff linter
        run: |
          source .venv/bin/activate
          echo "::group::Ruff Linting"
          ruff check src/dv
          echo "::endgroup::"
      
      - name: Check Ruff formatting
        run: |
          source .venv/bin/activate
          echo "::group::Ruff Format Check"
          ruff format --check src/dv
          echo "::endgroup::"
      
      - name: Format code if on pull request
        if: github.event_name == 'pull_request'
        run: |
          source .venv/bin/activate
          ruff format src/dv
      
      - name: Commit changes if formatting was applied
        if: github.event_name == 'pull_request'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --quiet || (git add src/dv && git commit -m "Apply ruff formatting" && git push)
